### ISSUE TITLE
npm-shrinkwrap.json causes unnecessary installs.

### ISSUE THREAD

**Issue by vramana** [daniellmb/console.style#7]
Basically all of your devDependencies all installed while doing `npm i console.style`. Would be help if you can some how manage them not to install.

**Comment by daniellmb** [comment]
Thanks for the heads up... Since not all projects on NPM follow [semantic versioning](http://semver.org/), I use shrinkwrap to help lock the versions so console.style work consistently over time. Not sure I want to remove it. You could just delete the `npm-shrinkwrap.json` file before running `npm install`.

**Comment by vramana** [comment]
How I can delete npm-shrinkwrap.json before `npm i console.style` ?? Can you change `dependencies` key in npm-shrinkwrap.json to `devDependencies` does that work??

**Comment by daniellmb** [comment]
@vramana I updated the shrink wrap to `devDependencies` and published as v0.2.2 let's see if that works.

**Comment by vramana** [comment]
It works :smile: Tthank you very much for the quick response.

**Comment by daniellmb** [comment]
:+1:
